---
- name: iniciando instalação dos pacotes php7.0
  hosts: operacao

  tasks:
    - name: instalando pacotes php7.0
      apt: name={{ item }} update_cache=yes state=present
      with_items: 
        - php7.0
        - php7.0-mysql
        - php7.0-curl
        - php7.0-json
        - php-memcached
        - php7.0-dev
        - php7.0-mcrypt 
        - php7.0-sqlite3
        - php7.0-mbstring
        - python-pip
        - python-mysqldb 

    - name: criando hello world PHP script
      copy: src=/root/index.php  dest=/var/www/html/index.php mode=0664 
