---

- name: Criacao do usuario para start do nginx
  hosts: desenvolvimento 
  vars:
    - username: nginusr
  tasks:
    - name: Criando usuario nos servidores.
      user: name={{ username }} shell=/bin/bash createhome=yes state=present
      tags: usuario_nginx
